### PR TITLE
Increase package version to v1.4.2

### PR DESCRIPTION
**Pull request by oschulz**
@dmbates / @andyferris Could we tag a new release? The compiler warnings fixed in #107 are starting to get annoying. :-)

### CODE REVIEW

**Comment by oschulz** [comment]
Fixes #108 (for non-developers :-) ).

**Review by dmbates — APPROVED** [review]
Looks good to me.  I agree that there should be a release to silence the warnings.

**Comment by oschulz** [comment]
Good to merge from my side.

**Comment by andyferris** [comment]
Thanks!

**Comment by oschulz** [comment]
Whoops, I messed up, it seems - Project.toml had already been at v1.4.2 and I increased to v1.4.3 now, so Registrator is not happy:

https://github.com/JuliaData/TypedTables.jl/pull/110#pullrequestreview-1361936176

Should we just reset the version to v1.4.2 in Project.toml and kickstart Registrator again?

**Comment by oschulz** [comment]
@andyferris could you trigger Registrator on https://github.com/JuliaData/TypedTables.jl/commit/5fd8ff2797122fce567fc0c77457c0dc0d949966, to register v1.4.2, and then re-trigger it on https://github.com/JuliaData/TypedTables.jl/commit/874ad06eb928787027e1cb86c1629a64b9832ed6 to register v1.4.3 after?

Sorry again for the mess.

**Comment by andyferris** [comment]
No no - don't be sorry, I do the same thing all the time :) Hopefully it's good now

**Comment by oschulz** [comment]
Thanks @andyferris ! :-)

**Pull request merged**
